### ISSUE TITLE
Question: For Olivia

### ISSUE THREAD

**Issue by trintiychristiana-eb** [trintiychristiana-eb/task-tracker#68]
Ask Olivia if we added content to the eb local databases (like users, because apparently I have a lot more than expected)

**Comment by trinitychristiana-eb** [comment]
> **TRINITY**: I have a curiosity question. When you were out on vacation, Delaine was trying to help me get an events page set up on qa, and we couldn't, but we did notice that I had a lot of rows in my eb local database (like is users in the user's table). My question is did we intentionally add content to that database because apparently I have more rows than expected...

> **OLIVIA**: That was likely added when we imported the data for event indexing (/d/ pages)
> **OLIVIA**: when we import that SQL dump

> **TRINITY**: Ahhh... Okay. That was just a question I had written down last week and forgot to ask you when you got back! Thanks for clarifying!
