### ISSUE TITLE
**QA Steps**

### ISSUE THREAD

**Issue by trinitychristiana-eb** [trintiychristiana-eb/task-tracker#81]
**QA Steps**
- [x] Make sure the LAUNCH_NEW_TOP_NAVIGATION_HEADER ff is on in QA
- [x] Make sure you have a way of monitoring GA hits. I use [this chrome extension](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna) to look at GA data.
- [x] Turn on the GA debugger or whatever tool you're using to view GA data.

**LOGGED OUT Steps**
- [x] Sign out of QA so that you're viewing the header as a logged out user.
- [ ] Go to an artist page in QA https://evbqa.com/a/2854. Make sure the header looks like the following screen shots
- [x] Open up your console:
     - Hover over the "Host an Event Menu" - hover over each of the links in that menu. Look at the GA logs. Each one should have an action of "HostAnEventLinkHovered", a category of "header" and a label corresponding to the text of the link.
     - Proceed to click on each of the links in the menu. Make sure each of the links goes to the correct place as defined by [this doc](https://docs.google.com/document/d/1OZHZelBZQO0qEwMyhe3_3nSM0vx-5pLa9Yrsw5f6HmE/edit?usp=sharing)
     - Look in the console for the GA actions fired. Each should have an action of "HostAnEventLinkClicked", a category of "header" and then labels that match the corresponding link title
- [ ] Hover over the help menu
     - Hover over each link in the help menu and see that GA actions fire with an action of "HelpLinkHovered", category of "header" and label corresponding to the link title
     - Click on each link. Make sure it goes to the correct place as defined by [this doc](https://docs.google.com/document/d/1OZHZelBZQO0qEwMyhe3_3nSM0vx-5pLa9Yrsw5f6HmE/edit?usp=sharing)
     - See that GA actions fire for each link with action "HelpLinkClicked", category of "header" and label corresponding to the link title
- [x] Hover over the Signin link 
     - See that the GA action of "SignInHovered", category of "header" and no label was fired
- [x] Click on the Signin link
     - See that the GA action of "SignInClicked", category of "header" and no label was fired and that you were taken to the signin page
- [x] Shrink the screen size down so that the header collapses. Make sure the narrow header looks like this
- [ ] Hover over each of the links in the header
     - See that GA actions were fired. There should not be an action for the "Browse Events" link as that's not part of this experiment. The GA actions are outlined in [this doc](https://docs.google.com/document/d/1OZHZelBZQO0qEwMyhe3_3nSM0vx-5pLa9Yrsw5f6HmE/edit?usp=sharing]
- [x] View the page as if you were on mobile
- [ ] Hover doesn't exist on mobile so click each of the links
     - See that GA actions were fired. There should not be an action for the "Browse Events" link as that's not part of this experiment. The GA actions are outlined in [this doc](https://docs.google.com/document/d/1OZHZelBZQO0qEwMyhe3_3nSM0vx-5pLa9Yrsw5f6HmE/edit?usp=sharing)
- [ ] Visit a trending search page https://evbqa.com/trending/searches/tn--nashville
     - Make sure the header looks like the screenshots above for both desktop and mobile
- [ ] Go to a collections page https://www.evbqa.com/c/made-for-nyc-food-lovers-cfcpq/
     - Make sure the header looks like the screenshots above for both desktop and mobile
- [ ] Go to a /covid-19 page https://www.evbqa.com/covid-19
     - Make sure the header looks like the screenshots above for both desktop and mobile
- [ ] Go to the /organizer/pricing page https://evbqa.com/organizer/pricing
     - Make sure the header looks like the screenshots above for both desktop and mobile
- [ ] Go to the compare packages page https://www.evbqa.com/organizer/compare-packages/
     - Make sure the header looks like the screenshots above for both desktop and mobile
- [ ] Go to a rally page https://www.evbqa.com/rally/11-things-boston-youre-single-valentines-day/
     - Make sure the header looks like the screenshots above for both desktop and mobile
- [x] Go to the /signin page https://evbqa.com/signin
     - Make sure the header looks like the screenshots above for both desktop and mobile
- [ ] Log into evbqa 

**LOGGED IN Steps**
- [ ] Now that you're logged in, go to an artist page https://evbqa.com/a/2854
     - The header should look the same as the screenshots above except that you should have an avatar in place of the "sign in" link. The Create Events CTA should not exist as a separate option in the menu
- [ ] Go to the /organizer/pricing page https://evbqa.com/organizer/pricing
     - The header should look the same as the screenshots above except that you should have an avatar in place of the "sign in" link. 

**MOBILE Steps**
- [ ] Although you've already used Chrome's tools to view something on mobile I think we should look at a few pages on a mobile device as well 
- [ ] Go to the /organizer/pricing page https://evbqa.com/organizer/pricing
     - Make sure the header looks like the screenshot above for mobile
- [ ] Visit a trending search page https://evbqa.com/trending/searches/tn--nashville
     - Make sure the header looks like the screenshots above for mobile

**REGRESSION Steps**
- [ ] Make sure the LAUNCH_NEW_TOP_NAVIGATION_HEADER ff is OFF in QA
- [ ] Go to the compare packages page https://www.evbqa.com/organizer/compare-packages/
- [ ] Make sure the header looks like this 
- [ ] Go to https://evbqa.com/a/2854 
- [ ] Make the header looks like this

**Comment by trintiychristiana-eb** [comment]
Artist page does not have the correct header

**Comment by trinitychristiana-eb** [comment]
Help find your tickets show this error but it goes to the correct URL (same for Contact an event organizer):
<img width="1655" alt="Screen Shot 2020-09-29 at 4 03 17 PM" src="https://user-images.githubusercontent.com/69914866/94615477-74d8fb00-026d-11eb-86e6-fa603de83902.png">

**Comment by trinitychristiana-eb** [comment]
Help Visit the help center takes me to http://qafull-eventbrite.cs64.force.com/support/?lg=en_US

**Comment by trinitychristiana-eb** [comment]
Hover events are not happening on the collapsed menu

**Comment by trinitychristiana-eb** [comment]
No GA actions happening on click with the collapsed header (happens otherwise)
